CREATE TABLE "employee" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"number" text NOT NULL,
	"name_ar" text NOT NULL,
	"name_en" text,
	"nationality" text,
	"id_type" text,
	"id_number" text,
	"id_expiry" date,
	"birth_date" date,
	"gender" text,
	"mobile" text,
	"email" text,
	"job_title_ar" text NOT NULL,
	"job_title_en" text,
	"department" text,
	"manager_id" uuid,
	"user_id" uuid,
	"work_location" text,
	"hire_date" date NOT NULL,
	"contract_type" text DEFAULT 'unlimited' NOT NULL,
	"contract_end_date" date,
	"employment_type" text DEFAULT 'full_time' NOT NULL,
	"probation_end_date" date,
	"annual_leave_days" integer DEFAULT 21 NOT NULL,
	"basic_salary" numeric(18, 2) DEFAULT '0' NOT NULL,
	"housing_allowance" numeric(18, 2) DEFAULT '0' NOT NULL,
	"transport_allowance" numeric(18, 2) DEFAULT '0' NOT NULL,
	"other_allowances" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"bank_name" text,
	"iban" text,
	"gosi_number" text,
	"status" text DEFAULT 'active' NOT NULL,
	"termination_date" date,
	"termination_reason" text,
	"offer_id" uuid,
	"notes" text,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" uuid,
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE TABLE "job_offer" (
	"id" uuid PRIMARY KEY DEFAULT uuidv7() NOT NULL,
	"tenant_id" uuid DEFAULT nullif(current_setting('app.tenant_id', true), '')::uuid NOT NULL,
	"number" text NOT NULL,
	"offer_date" date NOT NULL,
	"valid_until" date NOT NULL,
	"candidate_name_ar" text NOT NULL,
	"candidate_name_en" text,
	"nationality" text,
	"id_type" text,
	"id_number" text,
	"mobile" text,
	"email" text,
	"job_title_ar" text NOT NULL,
	"job_title_en" text,
	"department" text,
	"reports_to" text,
	"work_location" text,
	"contract_type" text DEFAULT 'unlimited' NOT NULL,
	"duration_months" integer,
	"employment_type" text DEFAULT 'full_time' NOT NULL,
	"start_date" date NOT NULL,
	"probation_days" integer DEFAULT 90 NOT NULL,
	"weekly_hours" integer DEFAULT 48 NOT NULL,
	"work_days" text,
	"annual_leave_days" integer DEFAULT 21 NOT NULL,
	"notice_days" integer,
	"basic_salary" numeric(18, 2) NOT NULL,
	"housing_allowance" numeric(18, 2) DEFAULT '0' NOT NULL,
	"transport_allowance" numeric(18, 2) DEFAULT '0' NOT NULL,
	"other_allowances" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"medical_insurance" text DEFAULT 'employee' NOT NULL,
	"annual_ticket" text DEFAULT 'none' NOT NULL,
	"other_benefits" text,
	"terms_ar" text,
	"notes" text,
	"status" text DEFAULT 'draft' NOT NULL,
	"approved_by" uuid,
	"approved_by_name" text,
	"approved_at" timestamp with time zone,
	"responded_at" date,
	"response_note" text,
	"cancelled_by" uuid,
	"cancelled_at" timestamp with time zone,
	"cancel_reason" text,
	"employee_id" uuid,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"created_by" uuid,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_by" uuid,
	"version" integer DEFAULT 1 NOT NULL
);
--> statement-breakpoint
CREATE UNIQUE INDEX "employee_number_uq" ON "employee" USING btree ("tenant_id","number");--> statement-breakpoint
CREATE UNIQUE INDEX "employee_id_number_uq" ON "employee" USING btree ("tenant_id","id_number") WHERE "employee"."id_number" is not null;--> statement-breakpoint
CREATE INDEX "employee_status_idx" ON "employee" USING btree ("tenant_id","status");--> statement-breakpoint
CREATE UNIQUE INDEX "job_offer_number_uq" ON "job_offer" USING btree ("tenant_id","number");--> statement-breakpoint
CREATE INDEX "job_offer_status_idx" ON "job_offer" USING btree ("tenant_id","status","offer_date");